image:
  file: .gitpod.Dockerfile

tasks:
  - name: "Load Enviornment Variables"
    init: mvn clean install
    command: eval $(gp env -e $(cat .env | xargs))

vscode:
  extensions:
    - redhat.vscode-xml
    - redhat.fabric8-analytics
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - hansuxdev.bootstrap5-snippets
