name: Build and deploy WAR app to Heroku

env:
  HEROKU_APP_NAME: your-app-name    # set this to the name of your Heroku App
  JAVA_VERSION: '11'                  # set this to the Java version to use

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.war'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - run: ll
      - run: sudo apt install -y tree
      - run: tree
#       - name: Deploy to Heroku
#         uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
#         with:
#           heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
#           heroku_app_name: ${{ env.HEROKU_APP_NAME }}
#           heroku_email: ${{ secrets.HEROKU_EMAIL }}
      
