name: Build and deploy WAR app to Heroku

env:
  HEROKU_APP_NAME: air-travel # set this to the name of your Heroku App
  JAVA_VERSION: "11" # set this to the Java version to use

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v2.3.1
        with:
          distribution: "zulu"
          java-version: ${{ env.JAVA_VERSION }}
          cache: "maven"

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: "${{ github.workspace }}/target/*.war"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - run: rm -r *
      - run: sudo apt install -y tree
      - run: tree

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - run: ls -l
      - run: sudo apt install -y tree
      - run: tree

      - name: Fetch the web app runner for Heroku
        run: wget https://search.maven.org/remotecontent?filepath=com/heroku/webapp-runner/9.0.52.1/webapp-runner-9.0.52.1.jar -O webapp-runner.jar

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ env.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          buildpack: heroku/java
          procfile: "web: java $JAVA_OPTS -jar webapp-runner.jar --port $PORT air.war"
